[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=👆🏻 ‍指定,https://raw.githubusercontent.com/suyunkai/ACL4SSR1/master/zhiding.list
ruleset=🤖 ‍OpenAI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🪙 ‍PayPal,https://raw.githubusercontent.com/suyunkai/ACL4SSR1/master/Clash/Ruleset/paypal.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/suyunkai/ACL4SSR/main/qiangnei.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=💩 ‍广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=💩 ‍广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=✈️ ‍起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=✈️ ‍起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🌍 媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🌍 媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=✈️ ‍起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🛩️ ‍墙内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🛩️ ‍墙内,[]GEOIP,LAN
ruleset=🛩️ ‍墙内,[]GEOIP,CN
ruleset=🌐 ‍未知,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=⚡ ‍低延迟`url-test`[🇦-🇿]{2}|^(?!.*(Data Left|Traffic|Expir[ey]|剩[余餘]流量|[到过過效]期|[时時][间間]|重置|官.?网|官方|产品|平台|勿连|修复|恢复|更新|地址|网站|网址|售后|客服|联系|使用|购买|公告|版本|出现|没网|情况|开通|数量|分割线|注[：:]))`.*`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=👆🏻 ‍指定`select`[]⚡ ‍低延迟`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`.*
custom_proxy_group=✈️ ‍起飞`select`[]⚡ ‍低延迟`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]👆🏻 ‍指定
custom_proxy_group=🤖 ‍OpenAI`select`[]🇺🇲 美国`[]🇭🇰 香港`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇸🇬 狮城`[]🇨🇳 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=🪙 ‍PayPal`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`[]🇺🇲 美国`[]🇭🇰 香港`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇸🇬 狮城`[]🇨🇳 台湾`[]🇯🇵 日本`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=🌍 媒体`select`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=🎮 游戏`select`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇺🇲 美国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=Ⓜ️ 微软`select`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇺🇲 美国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=Ⓜ️ 微软`select`[]✈️ ‍起飞`[]👆🏻 ‍指定`[]🇺🇲 美国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇰🇷 韩国`[]🛩️ ‍墙内
custom_proxy_group=🛩️ ‍墙内`select`[]DIRECT`[]REJECT`[]✈️ ‍起飞
custom_proxy_group=💩 ‍广告`select`[]REJECT`[]🛩️ ‍墙内`[]✈️ ‍起飞
custom_proxy_group=💩 ‍广告`select`[]REJECT`[]🛩️ ‍墙内`[]✈️ ‍起飞
custom_proxy_group=🌐 ‍未知`select`[]✈️ ‍起飞`[]⚡ ‍低延迟`[]🛩️ ‍墙内`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]👆🏻 ‍指定
custom_proxy_group=🇭🇰 香港`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=🇺🇲 美国`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`60,,150
custom_proxy_group=🇨🇳 台湾`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=🇸🇬 狮城`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=🇰🇷 韩国`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`60,,50
custom_proxy_group=🎏 ‍其他`url-test`^(?!.*(港|HK|Hong Kong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|KR|Korea|KOR|首尔|韩|韓)(?!.*(?!🇨🇳)[🇦-🇿]{2}))`https://i.ytimg.com/generate_204`60,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
